# Generated by Django 6.0 on 2026-06-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_userblogview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Update UserBlogView
        migrations.AlterModelOptions(
            name='userblogview',
            options={'ordering': ['-viewed_at'], 'unique_together': {('user', 'post')}},
        ),
        migrations.AddField(
            model_name='userblogview',
            name='reading_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userblogview',
            name='reached_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userblogview',
            name='is_valid_view',
            field=models.BooleanField(default=False),
        ),
        
        # Add fields to BadgeCategory
        migrations.AddField(
            model_name='badgecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badgecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Add fields to Badge
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='progress_type',
            field=models.CharField(choices=[('count', 'Count'), ('duration', 'Duration')], default='count', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='progress_target',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='reward_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'sort_order', 'level'], 'unique_together': {('category', 'level')}},
        ),
        
        # Add fields to UserBadge
        migrations.AddField(
            model_name='userbadge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='congratulatory_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'unique_together': {('user', 'badge')}},
        ),
        
        # Create ClaimedBadgeReward (new model not in 0001)
        migrations.CreateModel(
            name='ClaimedBadgeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to='infrastructure.badge')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to='infrastructure.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        
        # Add fields to BadgeSettings
        migrations.AddField(
            model_name='badgesettings',
            name='badges_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='badge_stats_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='max_visible_badges',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='sort_method',
            field=models.CharField(choices=[('level', 'By Level'), ('date_earned', 'By Date Earned'), ('rarity', 'By Rarity'), ('category', 'By Category')], default='level', max_length=20),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
