# Generated by Django 6.0 on 2026-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_badges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBadgeProgress',
        ),
    ]
