# Generated by Django 6.0 on 2025-12-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_manualorderrequest_location_order_deliver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualorderrequest',
            name='delivery_slot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
