# Generated by Django 6.0 on 2025-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_manualorderrequest_delivery_slot_order_delivery_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
