# Generated by Django 6.0 on 2026-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_blogreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
