# Generated by Django 6.0 on 2026-01-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_order_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
    ]
