# Generated by Django 6.0 on 2026-02-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0023_suspicious_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='infrastruct_ip_77357e_idx',
            old_name='infrastruct_ip_0f0927_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='infrastruct_last_se_9ad6c7_idx',
            old_name='infrastruct_last_see_d134d5_idx',
        ),
    ]
