# Generated by Django 6.0 on 2026-02-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0024_rename_infrastruct_ip_0f0927_idx_infrastruct_ip_77357e_idx_and_more'),
        ('infrastructure', '0024_suspicious_event_extra'),
    ]

    operations = [
    ]
