# Generated by Django 6.0 on 2026-02-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0024_suspicious_block_fields'),
        ('infrastructure', '0025_merge_20260219_2106'),
    ]

    operations = [
    ]
