# Generated by Django 6.0 on 2026-02-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0025_suspicious_enhancements'),
        ('infrastructure', '0026_merge_20260219_2235'),
    ]

    operations = [
    ]
