# Generated by Django 6.0 on 2026-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0029_blockedurl_blocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fastfood', 'Fast Food'), ('iranianfood', 'Iranian food'), ('bread', 'Bread')], default='slowfood', max_length=20),
        ),
    ]
