# Generated by Django 6.0 on 2026-06-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0030_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iranianfood', 'Iranian food'), ('fastfood', 'Fast Food'), ('bread', 'Bread'), ('pastries', 'Pastries'), ('cakes', 'Cakes'), ('appetizer', 'Appetizer')], default='slowfood', max_length=20),
        ),
    ]
