# Generated by Django 6.0 on 2026-06-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0033_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('iranianfood', 'Iranian food'), ('fastfood', 'Fast Food'), ('bread', 'Bread'), ('pastries', 'Pastries'), ('cake', 'Cakes'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert')], max_length=20, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
