# Generated by Django 6.0 on 2026-06-02 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_categorysort_product_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Slide Image (1920x1280 recommended)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Slide Title')),
                ('description', models.TextField(blank=True, verbose_name='Slide Description')),
                ('text_position', models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20, verbose_name='Text Position')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SlideshowMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mode Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Mode')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Currently Active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Button Text')),
                ('url', models.CharField(max_length=500, verbose_name='Button URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='infrastructure.slide')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='infrastructure.slideshowmode'),
        ),
    ]
