"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# مسیر پایه پروژه
BASE_DIR = Path(__file__).resolve().parent.parent

# امنیت
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-this-in-production')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
  # در حالت توسعه روشن باشه
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
# اپلیکیشن‌ها
INSTALLED_APPS = [
    'django.contrib.admin',            # پنل مدیریت جنگو
    'django.contrib.auth',             # سیستم احراز هویت جنگو
    'django.contrib.contenttypes',    # انواع داده‌ها و مدل‌ها
    'django.contrib.sessions',        # مدیریت نشست‌ها (session)
    'django.contrib.messages',        # پیام‌ها (مثلا خطا و اعلان)
    'django.contrib.staticfiles',     # مدیریت فایل‌های استاتیک (css/js)
    'social_django',
    'core.infrastructure',
]

# Middleware


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.interfaces.http.middleware.robots_middleware.RobotsNoIndexMiddleware",
]

# مسیر اصلی URL
ROOT_URLCONF = 'freshbread.urls'

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',

    # Custom pipeline for saving social auth email and provider
    'core.infrastructure.social.pipeline.save_email_provider',
)


# قالب‌ها
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # پوشه templates عمومی
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'freshbread.context_processors.cart_total_items',
                'freshbread.context_processors.cart_context',
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'freshbread.wsgi.application'

# دیتابیس (sqlite برای شروع – میشه بعداً MySQL یا PostgreSQL گذاشت)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}




# پسورد و امنیت
# اعتبارسنجی پسوردها
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # حداقل طول 8 کاراکتر
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# زبان و منطقه زمانی
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True




# کلید پیش‌فرض مدل‌ها
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# مسیر فایل‌های استاتیک (CSS, JS, تصاویر)

STATIC_URL = '/static/'

# اگر فولدر static پروژه داری
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# برای جمع‌آوری فایل‌ها (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"




# تنظیمات ایمیل (برای ارسال ایمیل تأیید و ...)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_TIMEOUT = 20


# لیست مدیران سایت (برای دریافت ارورها و ایمیل‌های مهم)
ADMINS = [
    ('Admin', os.getenv('ADMIN_EMAIL')),
]


# تنظیمات مربوط به احراز هویت و OAuth 

AUTHENTICATION_BACKENDS = [  
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',           # بک‌اند پیش‌فرض جنگو
    'social_core.backends.linkedin.LinkedinOAuth2',   # برای لینکدین
    'social_core.backends.xing.XingOAuth',           # ⚠ این Xing هست، برای X (توییتر) باید از توییتر استفاده کنیم
    'social_core.backends.twitter.TwitterOAuth',     # برای X (توییتر)
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',

]


# GitHub OAuth
SOCIAL_AUTH_GITHUB_KEY = os.getenv('SOCIAL_AUTH_GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('SOCIAL_AUTH_GITHUB_SECRET')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']


# Google OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

# LinkedIn OAuth
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY')
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET')

# Facebook OAuth
SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('SOCIAL_AUTH_FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET')

# Twitter OAuth
SOCIAL_AUTH_TWITTER_KEY = os.getenv('SOCIAL_AUTH_TWITTER_KEY')
SOCIAL_AUTH_TWITTER_SECRET = os.getenv('SOCIAL_AUTH_TWITTER_SECRET')

LOGIN_URL = '/auth/ru/'
LOGIN_REDIRECT_URL = '/auth/check_profile/'      # یا هر جایی که می‌خوای بعد از لاگین بره
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # one week
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://kingfood.ca').split(',')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'

MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = BASE_DIR / "media"
else:
    MEDIA_ROOT = Path("/usr/src/app/media")  # مسیر Volume لیارا

# تنظیمات Inbox پرداخت (برای بررسی پرداخت‌های ایمیلی)
PAYMENT_INBOX_USERNAME = os.getenv('PAYMENT_INBOX_USERNAME')
PAYMENT_INBOX_PASSWORD = os.getenv('PAYMENT_INBOX_PASSWORD')